// Do not edit this file!!!
// Your tests should go to a new file.

#include "big_integer.h"
#include <gmock/gmock.h>
#include <gtest/gtest.h>

TEST(Public, BigInteger) {
    EXPECT_EQ(compare(add(fromInt(256), fromInt(56)), fromInt(312)), Equal);
    EXPECT_ANY_THROW(subtract(fromInt(2), fromInt(1024)));
    EXPECT_EQ(toString(subtract(fromInt(968), fromInt(968))), "0");
}
