repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: 'Trim trailing whitespaces'
      - id: end-of-file-fixer
        name: 'Ensure proper end of files'
      - id: no-commit-to-branch
        name: 'Do not commit to "master"'
        args: [--branch, master]
      - id: check-merge-conflict
        name: 'Check for unresolved merge conflicts'

  - repo: https://github.com/Elentary/mirrors-run-clang-format
    rev: v14.0.6
    hooks:
    - id: run-clang-format
      name: 'Check formatting'
      args: ['--color', 'always']
