name: Test buildability
on:
  push:
    branches:
      - master
      - release-candidate

jobs:
  job:
    name: configure & build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and cache CMake
        uses: lukka/get-cmake@v.3.23.2

      - name: Check formatting
        uses: kalabukdima/clang-format-lint-action@master
        with:
          clangFormatVersion: 14

      - name: Build all
        run: cmake --preset default -DCLANG_TIDY_CHECK=ON && cmake --build --preset default
